name: UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Choose test type'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - specific
      specific_tests:
        description: 'Specify tests to run (e.g., tests/test_example.py)'
        required: false
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up test command
        id: test_command
        run: |
          if [ "${{ github.event.inputs.test_type }}" == "specific" ]; then
            echo "TEST_COMMAND=pytest ${{ github.event.inputs.specific_tests }}" >> $GITHUB_ENV
          else
            echo "TEST_COMMAND=pytest" >> $GITHUB_ENV
          fi

      - name: Run pytest with Selenium
        env:
          SELENIUM_URL: http://localhost:4444/wd/hub
        run: ${{ env.TEST_COMMAND }}

      - name: Upload test screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshots
          path: screenshots/